# ROS convention [x_m,y_m,theta_deg]
cfr:
  path_tracker:
    ros__parameters:
      waypoints:
        path_complex: "[
          [0, 0.3, 10],
          [0.5, 0.6, 0],
          [2.0, 3.0, 50],
          [-0.7, 4.0, 60],
          [-1.0, 4.5, 20],
          [-2.0, 1.5, 100],
          [-4.0, -0.5, 90],
          [-0.5, -3.5, 20],
          [-1.4, -4.5, 760],
          [-1.4, -6.0, -80]
          ]"
        path_forward_backward: "[
          [0.0, 0.0, 0],
          [1.0, 0.0, 0],
          [0.0, 0.0, 0],
          ]"
        path_left_right: "[
          [0.0, 0.0, 0],
          [0.0, 1.0, 0],
          [0.0, 0.0, 0],
          ]"
        path_s: "[
          [0.0, 0.0, 0],
          [2.0, 0.0, 0],
          [2.0, -0.5, 0],
          [0.0, -0.5, 0],
          [0.0, -1.0, 0],
          [2.0, -1.0, 0],
          ]"
        path_s_alternate: "[
          [0.0, 0.0, 0],
          [0.0, 2.0, 0],
          [0.5, 2.0, 0],
          [0.5, 0.0, 0],
          [1.0, 0.0, 0],
          [1.0, 2.0, 0],
          ]"
        path_45_deg: "[
          [2.0, 1.0, -90],
          [0.0, 3.0, -90],
          [1.0, 4.0, -90],
          [3.0, 2.0, -90],
          [4.0, 3.0, -90],
          [2.0, 5.0, -90],
          [3.0, 6.0, -90],
          [5.0, 4.0, -90],
          [6.0, 5.0, -90],
          [4.0, 7.0, -90],
          ]"
        path_L: "[
          [0.0, 0.0, 0],
          [1.0, 0.0, 0],
          [1.0, -1.0, 0],
          ]"
        use_id: 0

