cfr:
  path_tracker:
    ros__parameters:
      tracker_param:
        linear_x_P: 0.5
        linear_y_P: 0.5
        angular_z_P: 0.5

      tracker_twist_limit:
        max_linear_x: 1.0
        max_linear_y: 1.0
        max_angular_z: 0.5
        min_linear_x: -1.0
        min_linear_y: -1.0
        min_angular_z: -0.5

      tracker_target_tolerance:
        linear_x: 0.3
        linear_y: 0.3
        angular_z: 0.3
