# [x_m,y_m,theta_deg]
cfr:
  path_tracker:
    ros__parameters:
      waypoints: "[
        [0, 0.3, 10],
        [0.5, 0.6, 0],
        [2.0, 3.0, 50],
        [-0.7, 4.0, 60],
        [-1.0, 4.5, 20],
        [-2.0, 1.5, 100],
        [-4.0, -0.5, 90],
        [-0.5, -3.5, 20],
        [-1.4, -4.5, 760],
        [-1.4, -6.0, -80]
        ]"
